services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: netflix
      POSTGRES_PASSWORD: netflix
      POSTGRES_DB: netflix
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netflix -d netflix"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://netflix:netflix@db:5432/netflix
      CSV_PATH: /data/netflix.csv
      JWT_SECRET: please-change-me
    volumes:
      - ./data:/data:ro
    ports:
      - "8090:8000"

volumes:
  pgdata:
